### ISSUE TITLE
多个子元素选择器在同一组规则中出现时，若子元素选择器前无限定选择器，压缩后从第二个开始，其前面的空格会被去掉

### ISSUE THREAD

**Issue by librajt** [daxingplay/css-combo#22]
如以下css

``` css
a :nth-child(2), a :nth-child(5), a :nth-child(9) {display: none;}
```

压缩生成的代码为

``` css
a :nth-child(2),a:nth-child(5),a:nth-child(9){display:none}
```

空格被压缩，导致元素选择错误。版本为0.3.2
对比jar的压缩工具生成的代码，是没有问题的
